[package]
name = "background-task-example"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]

[dependencies]
futures = "0.1.21"
log = "0.4"

[dev-dependencies]
tokio = "0.1.6"
pretty_env_logger = "0.2.3"
